import { QueryResult } from 'pg';
import DB from '../../config/database';

/**
 * Input parameters and types
 * @param query Query string
 * @param values Array of values for the query
 */
// DBQUERY function - is used for all the queries in slugify. Returns and Console.logs either success resposne or error response
async function dbQuery(query: string, values: (string | number)[]): Promise<QueryResult> {
    // async/await
    try {
        const response = await DB.query(query, values);
        console.log('Success:');
        console.log(response.rows[0]);
        return response.rows[0];
    } catch (err) {
        console.log('Error: ');
        console.log(err.message);
        return err.message;
    }
}

/**
 * Input parameters and types
 * @param title User input string to be inserted into the column1
 * @param parent_id User input Parent Id of the category
 * @param slug Autogenretated slug
 * @param selectQuery Select query needs to include correct query string inlduing correct table and column1. column2 "slug" not needed as the check is done on title
 */
// Checks if parent_id and title unique constrain exist in the table
// and generates incrementing postfix number until not exist (title-1, title-2...)
// WHILE LOOP function
async function postfixLoop(
    title: string,
    parent_id: number,
    slug: string,
    selectQuery: string,
): Promise<Array<string>> {
    let selectValues: (string | number)[] = [title, parent_id];
    let newTitleSlug: string[];
    let i = 1;
    // eslint-disable-next-line no-constant-condition
    while (true) {
        i += 1;
        const newTitle = `${title}-${i}`;
        selectValues = [newTitle, parent_id];

        // eslint-disable-next-line no-await-in-loop
        const response = await dbQuery(selectQuery, selectValues);

        if (!response) {
            slug = `${slug}-${i}`;
            title = `${title}-${i}`;
            newTitleSlug = [title, slug];
            break;
        }
    }
    return newTitleSlug;
}

/**
 * Input parameters and types
 * @param input User input string to be inserted into the column1
 * @param input_parent_id User input Parent Id of the category
 * @param column1 1st column name for the user input string usually "title" DB yleisesti 
 * @param column2 2nd column name for the autogenerated slug usually "slug" DB
 * @param table The name of the table to be inserted DB
 */
// MAIN SLUGIFY function
async function slugify(
    input: string,
    input_parent_id: number,
    column1: string,
    column2: string,
    table?: string,
): Promise<void> {
    // Slugify the string
    let slug = input
        .normalize('NFD') // normalize()ing to NFD Unicode normal form decomposes combined graphemes into the combination of simple ones. The è of Crème ends up expressed as e +  ̀.
        .replace(/[\u0300-\u036f]/g, '') // Using a regex character class to match the U+0300 → U+036F range, it is now trivial to globally get rid of the diacritics, which the Unicode standard conveniently groups as the Combining Diacritical Marks Unicode block.
        .toLowerCase()
        .replace(/\s+/g, '-') // Replace spaces with -
        .replace(/[^\w-]+/g, '') // Removes anything not alphanumeric
        .replace(/\-\-+/g, '-'); // Replace multiple - with single -

    // First Select query - column2 "slug" not needed as the check is done on title
    const selectValues: (string | number)[] = [input, input_parent_id];
    const selectQuery = `SELECT ${column1} FROM ${table} WHERE ${column1} = $1 AND parent_id = $2`;
    const response = await dbQuery(selectQuery, selectValues);

    // Checks if parent_id and title unique constrain exist in the table and calls an postfixLoop() funtion if already exist.
    // postfixLoop generates the postfix number for the title and and the slug.
    if (response) {
        [input, slug] = await postfixLoop(input, input_parent_id, slug, selectQuery);
    }

    // Final Insert query into table
    const insertValues = [input_parent_id, input, slug];
    const insertQuery = `INSERT INTO ${table}(${column1}, parent_id, ${column2}) VALUES($2, $1, $3) RETURNING *`;

    await dbQuery(insertQuery, insertValues);
}

slugify('Test Titleäööö///and&&üÿü22', 81, 'title', 'slug', 'product_categories');
